### ISSUE TITLE
migration errors

### ISSUE THREAD

**Issue by globalavocado** [catarse/catarse#1704] opened 2015-08-19 22:28 UTC
Hello there, 

I'm on MacOSX and am able to perform the installation without any issues, inclusive of creating the databases.
When I then do 'rake db:migrate', rake is aborted at 20150729110132_add_team_members_view.rb, with the following error message:
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "("
LINE 55:             FILTER (WHERE c.was_confirmed)
This results in 7 pending migrations, as all following migrations are cancelled.

Can anyone please give me some pointers how to fix this?

**Comment by devton** [comment] 2015-08-19 22:46
@globalavocado i made a pull request fixing some things at this migration.

But this error i can't reproduce here, what is your postgresql version?

[]'s

**Comment by globalavocado** [comment] 2015-08-19 22:50
I am using postgresql 9.3.5

**Comment by devton** [comment] 2015-08-19 22:51
Catarse requires a lest postgresql 9.4 to run

**Comment by globalavocado** [comment] 2015-08-19 22:53
Okay thanks, I didn't know that. I will amend the Readme on my fork.
Hopefully it will solve it & also your pull request.

**Comment by devton** [comment] 2015-08-20 00:43
@globalavocado no problem, i think that you don't need to wait for my PR, just try direct with pg 9.4 :)

**Comment by devton** [comment] 2015-08-20 13:05
@globalavocado solved? closing this issue, feel free to reopen if not fixed ;)

**Closed by devton** 2015-08-20 13:05 UTC

**Comment by globalavocado** [comment] 2015-08-20 15:36
@devton everything's working find now, I just had the wrong version of psql. thanks for your help!

**Comment by hiteshranaut** [comment] 2016-11-26 13:03
I am using PostgreSQL 9.6.1 but getting same issue please help :(
